name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pylint
        id: pylint
        run: pylint *.py

      # - name: Capture Pylint Results
      #   run: echo "{pylint-results}={$(cat pylint.txt)}" >> $GITHUB_OUTPUT
      #   if: always()

  # analyze-results:
  #   needs: lint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Print Pylint Results
  #       run: |
  #         echo "Pylint Results: ${{ env.pylint-results }}"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Python Tests
        run: python3 -m unittest TestMortgageCalculator.py

  # Add a new job for the PR gate
  pr_gate:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run for pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests for PR gate
        run: |
          python -m unittest TestMortgageCalculator.py